CREATE TABLE Incomes
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    user_id     BIGINT       NOT NULL,
    amount      NUMERIC      NOT NULL,
    source      VARCHAR(255) NOT NULL,
    date        DATE         NOT NULL,
    description VARCHAR(255),
    frequency   VARCHAR(255) NOT NULL,
    end_date    DATE,
    CONSTRAINT fk_user FOREIGN KEY (user_id) REFERENCES Users (id)
)