CREATE TABLE Expense
(
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    user_id          BIGINT NOT NULL,
    amount           NUMERIC(15, 2) NOT NULL,
    category         VARCHAR(255) NOT NULL,
    date             DATE NOT NULL,
    description      VARCHAR(255),
    frequency        VARCHAR(255) NOT NULL,
    end_date         DATE,
    next_due_date    DATE,
    payment_method   VARCHAR(255) NOT NULL,
    CONSTRAINT pk_expense PRIMARY KEY (id),
    CONSTRAINT fk_expense_user FOREIGN KEY (user_id) REFERENCES Users (id)
);