CREATE TABLE savings
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    user_id     BIGINT                                  NOT NULL,
    amount      DECIMAL                                 NOT NULL,
    date        TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    goal        VARCHAR(255)                            NOT NULL,
    description VARCHAR(255),
    CONSTRAINT pk_savings PRIMARY KEY (id)
);

ALTER TABLE savings
    ADD CONSTRAINT FK_SAVINGS_ON_USER FOREIGN KEY (user_id) REFERENCES users (id);