version: "3.8"

services:
  db:
    image: postgres:15
    container_name: payments-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: paymentsdb
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - payments-network

volumes:
  db-data:

networks:
  payments-network: